name: instagram_app_clone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  firebase_storage: ^12.1.2
  equatable: ^2.0.5
  get_it: ^7.7.0
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  intl: ^0.19.0
  uuid: ^4.4.2
  cached_network_image: ^3.4.0
  fluttertoast: ^8.2.6
  toast: ^0.3.0
  modal_bottom_sheet: ^2.0.1
  firebase_core: ^3.3.0
  bloc: ^8.1.4
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.2.0
  #flutter_icons: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/instagram.png"

flutter:

  uses-material-design: true

  assets:
    - assets/.
    - assets/instagram.png


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

