// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnX50pHAtxlHIee1OAdnnYZuKYvqZ1jaM',
    appId: '1:249709472051:web:32a1919da3b962be23f646',
    messagingSenderId: '249709472051',
    projectId: 'instagram-app-clone-cec5f',
    authDomain: 'instagram-app-clone-cec5f.firebaseapp.com',
    storageBucket: 'instagram-app-clone-cec5f.appspot.com',
    measurementId: 'G-3CW5TWKYKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2K7M5wR_8Zv5R2zcPBzTrTdnd9NCbMps',
    appId: '1:249709472051:android:10c506abb43617bb23f646',
    messagingSenderId: '249709472051',
    projectId: 'instagram-app-clone-cec5f',
    storageBucket: 'instagram-app-clone-cec5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7hvRCJPoCuVzAwY-k-66LS9JxvGdmhcs',
    appId: '1:249709472051:ios:7d2c050ebaa27deb23f646',
    messagingSenderId: '249709472051',
    projectId: 'instagram-app-clone-cec5f',
    storageBucket: 'instagram-app-clone-cec5f.appspot.com',
    iosBundleId: 'com.example.instagramAppClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7hvRCJPoCuVzAwY-k-66LS9JxvGdmhcs',
    appId: '1:249709472051:ios:7d2c050ebaa27deb23f646',
    messagingSenderId: '249709472051',
    projectId: 'instagram-app-clone-cec5f',
    storageBucket: 'instagram-app-clone-cec5f.appspot.com',
    iosBundleId: 'com.example.instagramAppClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnX50pHAtxlHIee1OAdnnYZuKYvqZ1jaM',
    appId: '1:249709472051:web:64a906f37eb3118823f646',
    messagingSenderId: '249709472051',
    projectId: 'instagram-app-clone-cec5f',
    authDomain: 'instagram-app-clone-cec5f.firebaseapp.com',
    storageBucket: 'instagram-app-clone-cec5f.appspot.com',
    measurementId: 'G-BKEEXGCKN3',
  );
}
